export function printOverstayPDF(overstayLogs) {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const overstayHTML = overstayLogs.map((log, i) => `
        <tr style="border-bottom: 1px solid #E5E7EB;">
            <td style="padding: 10px; text-align: left;">${i + 1}</td>
            <td style="padding: 10px; text-align: left; font-family: monospace; font-weight: bold;">${log.plate}</td>
            <td style="padding: 10px; text-align: left;">${log.driver}</td>
            <td style="padding: 10px; text-align: left;">${log.zone}</td>
            <td style="padding: 10px; text-align: left; font-size: 12px; color: #4B5563;">${log.entry}</td>
            <td style="padding: 10px; text-align: left; font-size: 12px; color: #4B5563;">${log.exit || '--'}</td>
            <td style="padding: 10px; text-align: left;">
                <span style="display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 11px; font-weight: 600; 
                    ${log.status === 'Entered' ? 'background-color: #DEF7EC; color: #03543F;' : 'background-color: #F3F4F6; color: #374151;'}">
                    ${log.status || 'Entered'}
                </span>
            </td>
        </tr>
    `).join('');

    const pageContent = `
        <!DOCTYPE html>
        <html>
        <head>
            <title>UniPark - Overstay Alerts Report</title>
            <style>
                @media print {
                    body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
                }
                body {
                    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
                    color: #1F2937;
                    margin: 40px;
                    line-height: 1.5;
                }
                .header {
                    border-bottom: 2px solid #0066CC;
                    padding-bottom: 20px;
                    margin-bottom: 30px;
                }
                .logo-section {
                    display: flex;
                    align-items: center;
                    justify-content: space-between;
                }
                .title-main {
                    font-size: 24px;
                    font-weight: bold;
                    color: #0066CC;
                    margin: 0;
                }
                .title-sub {
                    font-size: 14px;
                    color: #4B5563;
                    margin: 5px 0 0 0;
                }
                .meta-grid {
                    display: grid;
                    grid-template-columns: repeat(2, 1fr);
                    gap: 10px;
                    margin-bottom: 30px;
                    font-size: 12px;
                    background-color: #F9FAFB;
                    padding: 15px;
                    border-radius: 8px;
                    border: 1px solid #E5E7EB;
                }
                table {
                    width: 100%;
                    border-collapse: collapse;
                    margin-top: 20px;
                }
                th {
                    background-color: #B45309;
                    color: white;
                    padding: 12px 10px;
                    font-size: 12px;
                    text-transform: uppercase;
                    letter-spacing: 0.05em;
                }
                td {
                    font-size: 13px;
                    border-bottom: 1px solid #E5E7EB;
                }
                .footer {
                    margin-top: 50px;
                    border-top: 1px solid #E5E7EB;
                    padding-top: 15px;
                    text-align: center;
                    font-size: 11px;
                    color: #9CA3AF;
                }
            </style>
        </head>
        <body>
            <div class="header">
                <div class="logo-section">
                    <div>
                        <h1 class="title-main">UniPark Strathmore</h1>
                        <p class="title-sub">Strathmore University Parking Management Portal</p>
                    </div>
                    <div style="text-align: right;">
                        <span style="font-weight: bold; color: #374151; font-size: 14px;">OVERSTAY ALERTS REPORT</span>
                    </div>
                </div>
            </div>

            <div class="meta-grid">
                <div><strong>Report Type:</strong> Overstay vehicles exceeding the selected threshold</div>
                <div><strong>Date Generated:</strong> ${new Date().toLocaleString()}</div>
                <div><strong>Total Alerts:</strong> ${overstayLogs.length} vehicles</div>
                <div><strong>Generated By:</strong> UniPark System Operator</div>
            </div>

            <table>
                <thead>
                    <tr>
                        <th style="width: 5%; text-align: left;">#</th>
                        <th style="width: 16%; text-align: left;">Plate Number</th>
                        <th style="width: 24%; text-align: left;">Driver Name</th>
                        <th style="width: 20%; text-align: left;">Parking Zone</th>
                        <th style="width: 20%; text-align: left;">Entry Time</th>
                        <th style="width: 10%; text-align: left;">Exit Time</th>
                        <th style="width: 5%; text-align: left;">Status</th>
                    </tr>
                </thead>
                <tbody>
                    ${overstayHTML}
                </tbody>
            </table>

            <div class="footer">
                <p>&copy; ${new Date().getFullYear()} Strathmore University UniPark. All rights reserved. Confidential Security Document.</p>
            </div>

            <script>
                window.onload = function() {
                    window.print();
                    setTimeout(() => { window.close(); }, 500);
                }
            </script>
        </body>
        </html>
    `;

    printWindow.document.write(pageContent);
    printWindow.document.close();
}

export function printLogsPDF(logs) {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const logsHTML = logs.map((log, i) => `
        <tr style="border-bottom: 1px solid #E5E7EB;">
            <td style="padding: 10px; text-align: left;">${i + 1}</td>
            <td style="padding: 10px; text-align: left; font-family: monospace; font-weight: bold;">${log.plate}</td>
            <td style="padding: 10px; text-align: left;">${log.driver}</td>
            <td style="padding: 10px; text-align: left;">${log.zone}</td>
            <td style="padding: 10px; text-align: left; font-size: 12px; color: #4B5563;">${log.entry}</td>
            <td style="padding: 10px; text-align: left; font-size: 12px; color: #4B5563;">${log.exit}</td>
            <td style="padding: 10px; text-align: left;">
                <span style="display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 11px; font-weight: 600; 
                    ${log.status === 'Entered' ? 'background-color: #DEF7EC; color: #03543F;' : 'background-color: #F3F4F6; color: #374151;'}">
                    ${log.status}
                </span>
            </td>
        </tr>
    `).join('');

    const pageContent = `
        <!DOCTYPE html>
        <html>
        <head>
            <title>UniPark - Vehicle Audit Logs</title>
            <style>
                @media print {
                    body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
                }
                body {
                    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
                    color: #1F2937;
                    margin: 40px;
                    line-height: 1.5;
                }
                .header {
                    border-bottom: 2px solid #0066CC;
                    padding-bottom: 20px;
                    margin-bottom: 30px;
                }
                .logo-section {
                    display: flex;
                    align-items: center;
                    justify-content: space-between;
                }
                .title-main {
                    font-size: 24px;
                    font-weight: bold;
                    color: #0066CC;
                    margin: 0;
                }
                .title-sub {
                    font-size: 14px;
                    color: #4B5563;
                    margin: 5px 0 0 0;
                }
                .meta-grid {
                    display: grid;
                    grid-template-columns: repeat(2, 1fr);
                    gap: 10px;
                    margin-bottom: 30px;
                    font-size: 12px;
                    background-color: #F9FAFB;
                    padding: 15px;
                    border-radius: 8px;
                    border: 1px solid #E5E7EB;
                }
                table {
                    width: 100%;
                    border-collapse: collapse;
                    margin-top: 20px;
                }
                th {
                    background-color: #0066CC;
                    color: white;
                    padding: 12px 10px;
                    font-size: 12px;
                    text-transform: uppercase;
                    letter-spacing: 0.05em;
                }
                td {
                    font-size: 13px;
                    border-bottom: 1px solid #E5E7EB;
                }
                .footer {
                    margin-top: 50px;
                    border-top: 1px solid #E5E7EB;
                    padding-top: 15px;
                    text-align: center;
                    font-size: 11px;
                    color: #9CA3AF;
                }
            </style>
        </head>
        <body>
            <div class="header">
                <div class="logo-section">
                    <div>
                        <h1 class="title-main">UniPark Strathmore</h1>
                        <p class="title-sub">Strathmore University Parking Management Portal</p>
                    </div>
                    <div style="text-align: right;">
                        <span style="font-weight: bold; color: #374151; font-size: 14px;">VEHICLE AUDIT LOGS</span>
                    </div>
                </div>
            </div>

            <div class="meta-grid">
                <div><strong>Report Type:</strong> Detailed Vehicle Entry/Exit Trail</div>
                <div><strong>Date Generated:</strong> ${new Date().toLocaleString()}</div>
                <div><strong>Total Logs Count:</strong> ${logs.length} entries</div>
                <div><strong>Generated By:</strong> UniPark System Operator</div>
            </div>

            <table>
                <thead>
                    <tr>
                        <th style="width: 5%; text-align: left;">#</th>
                        <th style="width: 15%; text-align: left;">Plate Number</th>
                        <th style="width: 25%; text-align: left;">Driver Name</th>
                        <th style="width: 20%; text-align: left;">Parking Zone</th>
                        <th style="width: 15%; text-align: left;">Entry Time</th>
                        <th style="width: 15%; text-align: left;">Exit Time</th>
                        <th style="width: 10%; text-align: left;">Status</th>
                    </tr>
                </thead>
                <tbody>
                    ${logsHTML}
                </tbody>
            </table>

            <div class="footer">
                <p>&copy; ${new Date().getFullYear()} Strathmore University UniPark. All rights reserved. Confidential Security Document.</p>
            </div>

            <script>
                window.onload = function() {
                    window.print();
                    setTimeout(() => { window.close(); }, 500);
                }
            </script>
        </body>
        </html>
    `;

    printWindow.document.write(pageContent);
    printWindow.document.close();
}

export function printAnalyticsPDF(metrics, zones) {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const zonesHTML = zones.map(z => {
        const available = z.total - z.occupied - z.reserved - z.cordoned;
        const pctOccupied = Math.round((z.occupied / z.total) * 100);
        return `
            <div style="border: 1px solid #E5E7EB; border-radius: 8px; padding: 15px; background-color: #FFFFFF; page-break-inside: avoid; margin-bottom: 15px;">
                <h3 style="margin: 0 0 10px 0; color: #0066CC; font-size: 16px;">${z.name} (Code: ${z.code})</h3>
                <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 8px; font-size: 12px; margin-bottom: 12px;">
                    <div><strong>Active Occupancy:</strong> ${z.occupied} / ${z.total} (${pctOccupied}%)</div>
                    <div><strong>Available Spaces:</strong> ${available < 0 ? 0 : available} bays</div>
                    <div><strong>Reserved Bays:</strong> ${z.reserved} spaces</div>
                    <div><strong>Cordoned Spaces:</strong> ${z.cordoned} spaces</div>
                </div>
                <div style="height: 8px; width: 100%; background-color: #F3F4F6; border-radius: 9999px; overflow: hidden;">
                    <div style="height: 100%; border-radius: 9999px; width: ${pctOccupied}%; 
                        background-color: ${pctOccupied >= 90 ? '#EF4444' : pctOccupied >= 70 ? '#F59E0B' : '#10B981'};">
                    </div>
                </div>
            </div>
        `;
    }).join('');

    const pageContent = `
        <!DOCTYPE html>
        <html>
        <head>
            <title>UniPark - Analytics Summary Report</title>
            <style>
                @media print {
                    body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
                }
                body {
                    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
                    color: #1F2937;
                    margin: 40px;
                    line-height: 1.5;
                }
                .header {
                    border-bottom: 2px solid #0066CC;
                    padding-bottom: 20px;
                    margin-bottom: 30px;
                }
                .logo-section {
                    display: flex;
                    align-items: center;
                    justify-content: space-between;
                }
                .title-main {
                    font-size: 24px;
                    font-weight: bold;
                    color: #0066CC;
                    margin: 0;
                }
                .title-sub {
                    font-size: 14px;
                    color: #4B5563;
                    margin: 5px 0 0 0;
                }
                .meta-grid {
                    display: grid;
                    grid-template-columns: repeat(2, 1fr);
                    gap: 10px;
                    margin-bottom: 30px;
                    font-size: 12px;
                    background-color: #F9FAFB;
                    padding: 15px;
                    border-radius: 8px;
                    border: 1px solid #E5E7EB;
                }
                .kpi-row {
                    display: grid;
                    grid-template-columns: repeat(4, 1fr);
                    gap: 15px;
                    margin-bottom: 30px;
                }
                .kpi-card {
                    background-color: #F9FAFB;
                    border: 1px solid #E5E7EB;
                    border-radius: 8px;
                    padding: 15px;
                    text-align: center;
                }
                .kpi-val {
                    font-size: 24px;
                    font-weight: bold;
                    color: #0066CC;
                    margin-top: 5px;
                }
                .kpi-lbl {
                    font-size: 11px;
                    color: #6B7280;
                    text-transform: uppercase;
                    font-weight: bold;
                }
                .grid-zones {
                    display: grid;
                    grid-template-columns: repeat(2, 1fr);
                    gap: 20px;
                }
                .section-title {
                    font-size: 18px;
                    font-weight: bold;
                    color: #374151;
                    border-left: 4px solid #0066CC;
                    padding-left: 10px;
                    margin: 30px 0 15px 0;
                }
                .footer {
                    margin-top: 50px;
                    border-top: 1px solid #E5E7EB;
                    padding-top: 15px;
                    text-align: center;
                    font-size: 11px;
                    color: #9CA3AF;
                }
            </style>
        </head>
        <body>
            <div class="header">
                <div class="logo-section">
                    <div>
                        <h1 class="title-main">UniPark Strathmore</h1>
                        <p class="title-sub">Strathmore University Parking Management Portal</p>
                    </div>
                    <div style="text-align: right;">
                        <span style="font-weight: bold; color: #374151; font-size: 14px;">ANALYTICS & OCCUPANCY REPORT</span>
                    </div>
                </div>
            </div>

            <div class="meta-grid">
                <div><strong>Report Type:</strong> Real-time Campus Parking Analytics</div>
                <div><strong>Date Generated:</strong> ${new Date().toLocaleString()}</div>
                <div><strong>Uptime Standard:</strong> 99.98% Network Operations</div>
                <div><strong>Generated By:</strong> UniPark System Operator</div>
            </div>

            <h2 class="section-title">Key Performance Indicators (KPIs)</h2>
            <div class="kpi-row">
                <div class="kpi-card">
                    <div class="kpi-lbl">Total Capacity</div>
                    <div class="kpi-val">${metrics.total}</div>
                </div>
                <div class="kpi-card">
                    <div class="kpi-lbl">Occupied Spots</div>
                    <div class="kpi-val" style="color: #F59E0B;">${metrics.occupied}</div>
                </div>
                <div class="kpi-card">
                    <div class="kpi-lbl">Reserved Spots</div>
                    <div class="kpi-val" style="color: #6366F1;">${metrics.reserved}</div>
                </div>
                <div class="kpi-card">
                    <div class="kpi-lbl">Occupancy Rate</div>
                    <div class="kpi-val" style="color: #10B981;">${metrics.occupancyRate}%</div>
                </div>
            </div>

            <h2 class="section-title">Campus Zones Summary</h2>
            <div class="grid-zones">
                ${zonesHTML}
            </div>

            <div class="footer">
                <p>&copy; ${new Date().getFullYear()} Strathmore University UniPark. All rights reserved. Confidential Security Document.</p>
            </div>

            <script>
                window.onload = function() {
                    window.print();
                    setTimeout(() => { window.close(); }, 500);
                }
            </script>
        </body>
        </html>
    `;

    printWindow.document.write(pageContent);
    printWindow.document.close();
}
